<?php
/**
 * @file
 * Code for the howest blog items feature.
 */

include_once 'howest_blog_items.features.inc';


/*
 * Implementation of hook_views_pre_render(&$view)
 */
function howest_blog_items_views_pre_render(&$view) {
  global $language;

  // Localize taxonomy terms in views
  foreach($view->result as $delta => $term ){
    if(isset($term->tid)) {
      i18n_string_translate_langcode( $language->language );
      $localized_term = i18n_taxonomy_localize_terms( taxonomy_term_load( $term->tid ));
      $term->tid = $localized_term->tid;
      $term->taxonomy_term_data_name = $localized_term->name;
    }
  }
}

/**
 * Implements hook_menu()
 *
 */
function howest_blog_items_menu() {
  $items['contact-us'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_howest_blog_items_form'),
    'access callback' => 'howest_blog_items_permission',
    'access arguments' => array(array('administrator', 'Content beheerder')),
    'title' => t('Send us your news!'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 *  Implements hook_permission()
 *
 */
function howest_blog_items_permission() {
  return array(
    'submit user generated blog item' => array(
      'title' => t('Submit a blog post'),
      'description' => t('Allows authorised users to submit unpublished blog items.'),
    ),
  );
}

/**
 * Provide a form to do things.
 *
 */
function _howest_blog_items_form() {
  $form = array();

  $content_voc = taxonomy_vocabulary_machine_name_load('content');
  $content_tree = taxonomy_get_tree($content_voc->vid);
  $content_tags = array();
  foreach ($content_tree as $tid => $term) {
    $content_tags[$term->tid] = $term->name;
  }

  $location_voc = taxonomy_vocabulary_machine_name_load('location');
  $location_tree = taxonomy_get_tree($location_voc->vid);
  $location_tags = array();
  foreach ($location_tree as $tid => $term) {
    $location_tags[$term->tid] = $term->name;
  }


  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#description' => '',
  );

  $form['location_tag'] = array(
    '#type' => 'select',
    '#title' => t('Locatie'),
    '#options' => $location_tags,
    '#required' => TRUE,
    '#description' => '',
  );

  $form['content_tag'] = array(
    '#type' => 'select',
    '#title' => t('Categorie'),
    '#options' => $content_tags,
    '#required' => TRUE,
    '#description' => '',
  );

  $form['body'] = array(
    '#title' => t('Content'),
    '#type' => 'text_format',
    '#default_value' => '',
    '#format' => 'full_html',
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit this form'),
  );

  return $form;
}


/**
 * submit handler
 *
 */
function _howest_blog_items_form_submit($form, &$form_state) {
  global $user;
  global $language;

  $node = new stdClass();
  $node->title = $form_state['values']['title'];
  $node->type = "blog_item";
  node_object_prepare($node);
  $node->language = $language->language;
  $node->body[LANGUAGE_NONE][0]['value']   = $form_state['values']['body']['value'];
  $node->body[LANGUAGE_NONE][0]['format']  = 'full_html';
  $node->uid = $user->uid;
  $node->status = 0;
  $node->promote = 0;
  $node->comment = 0;
  $node->field_content[LANGUAGE_NONE][]['tid'] = $form_state['values']['content_tag'];
  $node->field_location[LANGUAGE_NONE][]['tid'] = $form_state['values']['location_tag'];

  $node = node_submit($node); // Prepare node for saving
  node_save($node);

 // watchdog('info', $watchdog);
  drupal_set_message(t('Your news item has been submitted. Thanks!'));
}