<?php
/**
 * @file
 * Code for the Howest Newsletter settings feature.
 */

include_once 'howest_newsletter_settings.features.inc';

/**
 * Implementation of hook_menu
 */
function howest_newsletter_settings_menu()
{
  $items['access-denied'] = array(
    'title' => 'Access denied',
    'description' => t('Access denied'),
    'page callback' => 'howest_newsletter_settings_access_denied',
    'access callback' => TRUE
  );

  return $items;
}

function howest_newsletter_settings_access_denied() {
  drupal_set_title(howest_newsletter_settings_get_access_denied_title()); 
  
  return array(
    'type' => 'markup',
    '#markup' => howest_newsletter_settings_get_access_denied_msg()
  );
}

/**
 * Implements hook_variable_info().
 */
function howest_newsletter_settings_variable_info($options) {
  $variables['howest_newsletter_settings_access_denied_msg'] = array(
    'type' => 'array',
    'title' => t('Access denied message'),
    'default' => array('*' => 0),
    'description' => t('Access denied message'),
    'required' => TRUE,
    'localize' => TRUE,
    'group' => 'site_information',
  );

  $variables['howest_newsletter_settings_access_denied_title'] = array(
    'type' => 'array',
    'title' => t('Access denied title'),
    'default' => array('*' => 0),
    'description' => t('Access denied title'),
    'required' => TRUE,
    'localize' => TRUE,
    'group' => 'site_information',
  );

  return $variables;
}

function howest_newsletter_settings_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'system_site_information_settings') {
    $form['howest_newsletter_settings_access_denied_title'] = array(
      '#type' => 'textfield',
      '#title' => t('Access denied title'),
      '#default_value' => howest_newsletter_settings_get_access_denied_title(TRUE),
    );

    $form['howest_newsletter_settings_access_denied_msg'] = array(
      '#type' => 'text_format',
      '#format' => 'full_html',
      '#title' => t('Access denied message'),
      '#default_value' => howest_newsletter_settings_get_access_denied_msg(TRUE),
    );

    $form['#submit'][] = 'howest_newsletter_settings_form_submit';
  }
}

function howest_newsletter_settings_form_submit($form, &$form_state){
    $values = $form_state['values'];

    if (!empty($values['howest_newsletter_settings_access_denied_msg']['value'])) {
      variable_set('howest_newsletter_settings_access_denied_msg', $values['howest_newsletter_settings_access_denied_msg']['value']);
    }
}

function howest_newsletter_settings_get_access_denied_title($settings = FALSE) {
  global $language;

  if ($settings && array_key_exists('variable_realm_key_language', $_GET)) {
    $language_var = $_GET['variable_realm_key_language'];
  }
  else {
    $language_var = $language->language;
  }

  $msg = i18n_variable_get('howest_newsletter_settings_access_denied_title', $language_var, 'Howest newsletter');

  return $msg;
}

function howest_newsletter_settings_get_access_denied_msg($settings = FALSE) {
  global $language;

  if ($settings && array_key_exists('variable_realm_key_language', $_GET)) {
    $language_var = $_GET['variable_realm_key_language'];
  }
  else {
    $language_var = $language->language;
  }

  $msg = i18n_variable_get('howest_newsletter_settings_access_denied_msg', $language_var, array());

  if (array_key_exists('value', $msg)) {
    return $msg['value']; 
  }

  return 'Access denied';
}

function howest_newsletter_settings_block_info() {
  $blocks['deadline'] = array(
    'info' => t('Deadline'),
    'region' => 'sidebar_first',
  );

  return $blocks;
}

function howest_newsletter_settings_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'deadline':
      
      if (user_access('access content')) {
        $block['subject'] = l('Deadlines', 'deadlines');
        $block['content'] = array(
          '#type' => 'markup',
          '#markup' => '',
        );
      }

      break;
  }

  return $block;
}
